kind: pipeline
name : LLVM Toolchain Compiler
version: rev1.5_template
steps:
 - name: LLVM-tc Compilation
   image: xyzuan/xdocker:latest
   environment:
     LLVM_NAME:
       from_secret: LLVM_NAME
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     GH_USERNAME:
       from_secret: GH_USERNAME
     GH_EMAIL:
       from_secret: GH_EMAIL
     GH_TOKEN:
       from_secret: GH_TOKEN
     GL_TOKEN:
       from_secret: GL_TOKEN
     GH_PUSH_REPO_URL:
       from_secret: GH_PUSH_REPO_URL
     GL_PUSH_REPO_URL:
       from_secret: GL_PUSH_REPO_URL
   commands:
          - cp -af sources.list /etc/apt/
          - apt-get autoremove -y && apt-get --purge remove -y && apt-get autoclean -y && apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y
          - bash llvm-tc_build.sh
