kind: pipeline
name : LLVM Toolchain Compiler
version: rev1.5_template
steps:
 - name: LLVM-tc Compilation
   image: ubuntu:latest
   environment:
     LLVM_NAME:
       from_secret: LLVM_NAME
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     GH_USERNAME:
       from_secret: GH_USERNAME
     GH_EMAIL:
       from_secret: GH_EMAIL
     GH_TOKEN:
       from_secret: GH_TOKEN
     GL_TOKEN:
       from_secret: GL_TOKEN
     GH_PUSH_REPO_URL:
       from_secret: GH_PUSH_REPO_URL
     GL_PUSH_REPO_URL:
       from_secret: GL_PUSH_REPO_URL
   commands:
     - cp -af sources.list /etc/apt/
     - apt-get update && apt-get upgrade -y
     - ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
     - apt-get install -y bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev
     - bash llvm-tc_build.sh
